server.port: 8081

# Producer properties
spring:
  kafka:
    enable: true
    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      bootstrap-servers: 127.0.0.1:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      group-id: group_id

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql

    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: create.sql
              action: create
            create-source: metadata
  flyway:
    url : 'jdbc:postgresql://localhost:5432/mn'
    password: postgres
    user: postgres
    baselineOnMigrate: true
    schemas: public

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mn
    username: postgres
    password: postgres

topic:
  name: payment



